NFL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

core/urls.py
from core import views
from django.urls import path

from .models import *

app_name = "core"
urlpatterns = [
    path('list/stadiums/',views.ListStadium.as_view(), name="listS"),
    path('create/Stadiums/',views.CreateStadium.as_view(), name="createS"),
    path('detail/Stadiums/<int:pk>/', views.DetailStadium.as_view(), name= "detailS"),
    path('update/Stadiums/<int:pk>/', views.UpdateStadium.as_view(), name= "UpdateS"),
    path('delete/Stadiums/<int:pk>/', views.DeleteStadium.as_view(), name= "deleteS"),
    
    path('list/Teams/',views.ListTeam.as_view(), name="listT"),
    path('create/Teams/',views.CreateTeam.as_view(), name="createT"),
    path('detail/Teams/<int:pk>/', views.DetailTeam.as_view(), name= "detailT"),
    path('update/Teams/<int:pk>/', views.UpdateTeam.as_view(), name= "UpdateT"),
    path('delete/Teams/<int:pk>/', views.DeleteTeam.as_view(), name= "deleteT"),
    
    path('list/Owners/',views.ListOwners.as_view(), name="listO"),
    path('create/Owners/',views.CreateOwners.as_view(), name="createO"),
    path('detail/Owners/<int:pk>/', views.DetailOwners.as_view(), name= "detailO"),
    path('update/Owners/<int:pk>/', views.UpdateOwners.as_view(), name= "UpdateO"),
    path('delete/Owners/<int:pk>/', views.DeleteOwners.as_view(), name= "deleteO"),
    
    path('list/Players/',views.ListPlayers.as_view(), name="listP"),
    path('list/TeamPlayers/',views.ListTeamsPlayers.as_view(), name="listTP"),
    path('create/Players/',views.CreatePlayers.as_view(), name="createP"),
    path('detail/Players/<int:pk>/', views.DetailPlayers.as_view(), name= "detailP"),
    path('update/Players/<int:pk>/', views.UpdatePlayers.as_view(), name= "UpdateP"),
    path('delete/Players/<int:pk>/', views.DeletePlayers.as_view(), name= "deleteP"),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"
urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('information/', views.Information.as_view(), name="information"),
]

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<style>
  body {
    color: aliceblue;
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    margin: 0;
    background-color: black;
    background-image: url(https://wallpapers.com/images/high/cool-nfl-red-and-black-pueomuyjpqb33bgk.webp);
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
  }

  thead {
    color: aliceblue;
    background-color: rgba(0, 0, 0, 0.5);
  }

  thead {
    color: aliceblue;
    background-color: rgba(0, 0, 0, 0.5);
  }
  
  tbody {
    color: aliceblue;
    background-color: rgba(0, 0, 0, 0.5);
  }

</style>
<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary navbar-transparent"> 
    <a class="navbar-brand" href="{% url 'home:index' %}">NFL of Ray</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home:index' %}">Inicio</a>
        </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:listO' %}">Dueños/Propietarios</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:listT' %}">Equipos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:listP' %}">Jugadores</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:listTP' %}">Jugadores_Equipos</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:listS' %}">Estadios</a>
          </li>
         
           
        </ul>
    </div>
</nav>
      {% block content %}
      {% endblock content %}
      <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <footer class="text-center text-white" >
            <!-- Grid container -->
            <div class="container pt-4">
              <!-- Section: Social media -->
              <section class="mb-4">
                <!-- Facebook -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-facebook-f"></i
                ></a>
          
                <!-- Twitter -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-twitter"></i
                ></a>
          
                <!-- Google -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-google"></i
                ></a>
          
                <!-- Instagram -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-instagram"></i
                ></a>
          
                <!-- Linkedin -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-linkedin"></i
                ></a>
                <!-- Github -->
                <a
                  class="btn btn-link btn-floating btn-lg text-dark m-1"
                  href="#!"
                  role="button"
                  data-mdb-ripple-color="dark"
                  ><i class="fab fa-github"></i
                ></a>
              </section>
              <!-- Section: Social media -->
            </div>
            <!-- Grid container -->
          
            <!-- Copyright -->
            <div class="text-center text-dark p-3" style="background-color: white;">
              © 2023 Copyright: NFL y asociados
              <a class="text-dark" href="https://mdbootstrap.com/"></a>
            </div>
            <!-- Copyright -->
          </footer>
</body>
</html>