NFL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

core/urls.py
from core import views
from django.urls import path

from .models import *

app_name = "core"
urlpatterns = [
    path('list/stadiums/',views.ListStadium.as_view(), name="listS"),
    path('create/Stadiums/',views.CreateStadium.as_view(), name="createS"),
    path('detail/Stadiums/<int:pk>/', views.DetailStadium.as_view(), name= "detailS"),
    path('update/Stadiums/<int:pk>/', views.UpdateStadium.as_view(), name= "UpdateS"),
    path('delete/Stadiums/<int:pk>/', views.DeleteStadium.as_view(), name= "deleteS"),
    
    path('list/Teams/',views.ListTeam.as_view(), name="listT"),
    path('create/Teams/',views.CreateTeam.as_view(), name="createT"),
    path('detail/Teams/<int:pk>/', views.DetailTeam.as_view(), name= "detailT"),
    path('update/Teams/<int:pk>/', views.UpdateTeam.as_view(), name= "UpdateT"),
    path('delete/Teams/<int:pk>/', views.DeleteTeam.as_view(), name= "deleteT"),
    
    path('list/Owners/',views.ListOwners.as_view(), name="listO"),
    path('create/Owners/',views.CreateOwners.as_view(), name="createO"),
    path('detail/Owners/<int:pk>/', views.DetailOwners.as_view(), name= "detailO"),
    path('update/Owners/<int:pk>/', views.UpdateOwners.as_view(), name= "UpdateO"),
    path('delete/Owners/<int:pk>/', views.DeleteOwners.as_view(), name= "deleteO"),
    
    path('list/Players/',views.ListPlayers.as_view(), name="listP"),
    path('list/TeamPlayers/',views.ListTeamsPlayers.as_view(), name="listTP"),
    path('create/Players/',views.CreatePlayers.as_view(), name="createP"),
    path('detail/Players/<int:pk>/', views.DetailPlayers.as_view(), name= "detailP"),
    path('update/Players/<int:pk>/', views.UpdatePlayers.as_view(), name= "UpdateP"),
    path('delete/Players/<int:pk>/', views.DeletePlayers.as_view(), name= "deleteP"),
]

core/models.py
from django.db import models

# Create your models here.

##Se crean modelos para poder trabajar con los requerimientos pedidos en la descripcion del programa
class Owner(models.Model):
    numero=models.IntegerField(primary_key=True)
    nombre=models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'Owners'
        
class Teams(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=128, blank=True, null=True)
    sede = models.CharField(max_length=256, blank=True, null=True)
    propietario=models.ForeignKey(Owner, on_delete=models.CASCADE, db_column='numero')

    class Meta:
        managed = True
        db_table = 'Team'    
    def __str__(self):
        return self.nombre

class Players(models.Model):
    numero=models.IntegerField(primary_key=True)
    nombreC=models.CharField(max_length=128, blank=True, null=True)
    posicion=models.CharField(max_length=64, blank=True, null=True)
    equipo=models.ForeignKey(Teams, on_delete=models.CASCADE, db_column='codigo')

    class Meta:
        managed = True
        db_table = 'Player'
    def __str__(self):
        return self.nombreC

class Stadiums(models.Model):
    codigo = models.IntegerField(primary_key=True)  
    nombre = models.CharField(max_length=128, blank=True, null=True)
    capacidad= models.IntegerField(blank=True, null=True)
    largo= models.IntegerField(blank=True, null=True)
    ancho=models.IntegerField(blank=True, null=True)
    propietario=models.ForeignKey(Owner, on_delete=models.CASCADE, db_column='numero')
    
    class Meta:
        managed = True
        db_table = 'Stadium'
    def __str__(self):
        return self.nombre

core/forms.py
from django import forms

from .models import Owner, Players, Stadiums, Teams

class OwnersForm(forms.ModelForm):
    class Meta:
        model = Owner
        fields = "__all__"
        Exclude=[]
        widgets = {
            "numero": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Ingrese el número del propietario"}),
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del propietario"}),
        }

class UpdateOwnersForm(forms.ModelForm):
    class Meta:
        model = Owner
        fields = "__all__"
        exclude=["numero"]
        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nuevo nombre del propietario"}),
        }

class PlayersForm(forms.ModelForm):
    class Meta:
        model = Players
        fields = "__all__"
        exclude = []
        widgets = {
            "numero": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Ingrese el número del jugador"}),
            "nombreC": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre completo del jugador"}),
            "posicion": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese la posicion del jugador"}),
            "equipo": forms.Select(attrs={"class": "form-control"}),
        }

class UpdatePlayersForm(forms.ModelForm):
    class Meta:
        model = Players
        fields = "__all__"
        exclude = []
        widgets = {
            "numero": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Ingrese el nuevo número del jugador"}),
            "nombreC": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nuevo nombre del jugador"}),
            "posicion": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese la nueva posicion del jugador"}),
            "equipo": forms.Select(attrs={"class": "form-control"}),
        }


class StadiumForm(forms.ModelForm):
    class Meta:
        model = Stadiums
        fields = "__all__"
        exclude = []
        widgets = {
            "codigo": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el número del estadio"}),
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del estadio"}),
            "capacidad": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Ingrese la capacidad de personas del estadio"}),
            "largo": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Ingrese el Largo del estadio (yd)"}),
            "ancho": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Ingrese el Ancho del estadio (yd)"}),
            "propietario": forms.Select(attrs={"class": "form-control"}),
        }

class UpdateStadiumForm(forms.ModelForm):
    class Meta:
        model = Stadiums
        fields = "__all__"
        exclude = []
        widgets = {
            "codigo": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nuevo número del estadio"}),
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nuevo nombre del estadio"}),
            "capacidad": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Ingrese la nueva capacidad de personas del estadio"}),
            "largo": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Ingrese el nuevo Largo del estadio (yd)"}),
            "ancho": forms.NumberInput(attrs={"type": "number", "class": "form-control", "placeholder": "Ingrese el nuevo Ancho del estadio (yd)"}),
            "propietario": forms.Select(attrs={"class": "form-control"}),
        }

class TeamForm(forms.ModelForm):
    class Meta:
        model = Teams
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nombre del equipo"}),
            "sede": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la descripción de la liga"}),
            "propietario": forms.Select(attrs={"class": "form-control"}),
        }

class UpdateTeamForm(forms.ModelForm):
    class Meta:
        model = Teams
        fields = "__all__"
        exclude = ["codigo"]
        widgets = {
            "nombre": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Ingrese el nuevo nombre del equipo"}),
            "sede": forms.Textarea(attrs={"class": "form-control", "rows": 3, "placeholder": "Ingrese la nueva descripción de la liga"}),
            "propietario": forms.Select(attrs={"class": "form-control"}),
        }

####class RelationshipForm(models.Model):
    #Stadium = models.ForeignKey(Stadium, on_delete=models.CASCADE)
    #Team = models.ForeignKey(Team, on_delete=models.CASCADE)
    #Players=models.ForeignKey(Players, on_delete=models.CASCADE)
    #Owners=models.ForeignKey(Owners, on_delete=models.CASCADE)

core/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from .forms import *
from .models import Stadiums, Owner, Teams, Players

# Create your views here.

####Estadios

class ListStadium(generic.View):
    template_name = "core/listS.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Stadiums.objects.all()
        self.context = {
            "Stadiums": queryset  
        }
        return render(request, self.template_name, self.context)



class DetailStadium(generic.DetailView):
    template_name = "core/detailS.html"
    model = Stadiums

    def stadium_detail(request, codigo):
        stadium = get_object_or_404(Stadiums, codigo=codigo)
        return render(request, 'detailS.html', {'stadium': stadium})

class CreateStadium(generic.CreateView):
    template_name = "core/createS.html"
    model = Stadiums
    form_class = StadiumForm
    success_url = reverse_lazy("core:listS")


class UpdateStadium(generic.UpdateView):
    template_name = "core/UpdateS.html"
    model = Stadiums
    form_class = UpdateStadiumForm
    success_url = reverse_lazy("core:listS")

class DeleteStadium(generic.DeleteView):
    template_name = "core/deleteS.html"
    model = Stadiums
    success_url = reverse_lazy("core:listS")


####Equipos

class ListTeam(generic.View):
    template_name = "core/listT.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Teams.objects.all()
        self.context = {
            "Teams": queryset
        }
        return render(request, self.template_name,self.context)
    
class CreateTeam(generic.CreateView):
    template_name = "core/createT.html"
    model = Teams
    form_class = TeamForm
    success_url = reverse_lazy("core:listT")

    def form_valid(self, form):
        
        return super().form_valid(form)


class DetailTeam(generic.DetailView):
    template_name = "core/detailT.html"
    model = Teams
    
    def detail_team(request, pk):
        teams = get_object_or_404(teams, pk=pk)
        return render(request, 'detailT.html', {'Teams': teams})

class UpdateTeam(generic.UpdateView):
    template_name = "core/UpdateT.html"
    model = Teams
    form_class = UpdateTeamForm
    success_url = reverse_lazy("core:listT")

class DeleteTeam(generic.DeleteView):
    template_name = "core/deleteT.html"
    model = Teams
    success_url = reverse_lazy("core:listT")

####Dueños

class ListOwners(generic.View):
    template_name = "core/listO.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Owner.objects.all()
        self.context = {
            "Owners": queryset
        }
        return render(request, self.template_name,self.context)
    
class CreateOwners(generic.CreateView):
    template_name = "core/createO.html"
    model = Owner
    form_class = OwnersForm
    success_url = reverse_lazy("core:listO")

    def form_valid(self, form):
        return super().form_valid(form)


class DetailOwners(generic.DetailView):
    template_name = "core/detailO.html"
    model = Owner

    def detail_owner(request, pk):
        owner = get_object_or_404(owner, pk=pk)
        return render(request, 'detailO.html', {'Owner': owner})


class UpdateOwners(generic.UpdateView):
    template_name = "core/UpdateO.html"
    model = Owner
    form_class = UpdateOwnersForm
    success_url = reverse_lazy("core:listO")

class DeleteOwners(generic.DeleteView):
    template_name = "core/deleteO.html"
    model = Owner
    success_url = reverse_lazy("core:listO")

####Jugadores

class ListPlayers(generic.View):
    template_name = "core/listP.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Players.objects.all()
        self.context = {
            "Players": queryset
        }
        return render(request, self.template_name,self.context)
    
class CreatePlayers(generic.CreateView):
    template_name = "core/createP.html"
    model = Players
    form_class = PlayersForm
    success_url = reverse_lazy("core:listP")

    def form_valid(self, form):
        
        return super().form_valid(form)


class DetailPlayers(generic.DetailView):
    template_name = "core/detailP.html"
    model = Players

class UpdatePlayers(generic.UpdateView):
    template_name = "core/UpdateP.html"
    model = Players
    form_class = UpdatePlayersForm
    success_url = reverse_lazy("core:listP")

class DeletePlayers(generic.DeleteView):
    template_name = "core/deleteP.html"
    model = Players
    success_url = reverse_lazy("core:listP")
    
####Jugadores equipos

class ListTeamsPlayers(generic.View):
    template_name = "core/team_players.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = Players.objects.all()
        self.context = {
            "Players": queryset
        }
        return render(request, self.template_name,self.context)

templates/core/UpdateP.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Jugadores
{% endblock title %}

{% block content %}
<h1>Actualizar Jugador</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <br>
  <button type="submit" class="btn btn-outline-primary">Actualizar Jugador</button>
  <a href="{% url 'core:listP' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

templates/core/UpdateT.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar equipos
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <br>
        <button type="submit" class="btn btn-outline-primary">Actualizar equipo</button>
        <a href="{% url 'core:listT' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

templates/core/createP.html
{% extends "base/base.html" %}

{% block title %}
Añadir Jugadores
{% endblock title %}

{% block content %}
<h1>Agregar Jugador</h1>
<form method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <br>
  <button type="submit" class="btn btn-outline-success">Añadir Jugador</button>
  <a href="{% url 'core:listP' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

templates/core/createS.html
{% extends "base/base.html" %}

{% block title %}
Añadir estadio de futbol
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <br>
        <button type="submit" class="btn btn-outline-success">Añadir estadio</button>
        <a href="{% url 'core:listS' %}" class="btn btn-outline-warning">Cancelar</a>
    </form>
{% endblock content %}

templates/core/createT.html
{% extends "base/base.html" %}

{% block title %}
Añadir equipo de futbol
{% endblock title %}

{% block content %}
<form action="" method="post" class="form">
  {% csrf_token %}
  {{ form.as_p }}
  <br>
  <button type="submit" class="btn btn-outline-success">Añadir Equipo</button>
  <a href="{% url 'core:listT' %}" class="btn btn-outline-warning">Cancelar</a>
</form>

{% endblock content %}

templates/core/deleteP.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Jugadores
{% endblock title %}

{% block content %}
<p>¿Desea eliminar el Jugador {{ object.nombreC }}?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Continuar</button>
  <a href="{% url 'core:listP' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

templates/core/deleteS.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar estadio
{% endblock title %}

{% block content %}
<br>
<p>¿Desea eliminar el estadio {{ object.nombre }}?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Yes, Continuar</button>
  <a href="{% url 'core:listS' %}" class="btn btn-outline-warning">Cancelar</a>
</form>


{% endblock content %}

templates/core/deleteT.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar equipo
{% endblock title %}

{% block content %}
<p>¿Desea eliminar el equipo {{ object.nombre }}?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-outline-danger">Continuar</button>
  <a href="{% url 'core:listT' %}" class="btn btn-outline-warning">Cancelar</a>
</form>
{% endblock content %}

templates/core/detailP.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del jugador
{% endblock title %}


{% block content %}
<h1>Detalles del jugador</h1>
      <p>Numero: {{ players.numero }}</p>
      <p>Nombre: {{ players.nombreC }}</p>
      <p>Posicion: {{ players.posicion }}</p>
      <p>Equipo: {{ players.equipo.nombre }}</p>
  <a href="{% url 'core:listP' %}" class="btn btn-outline-warning">Regresar</a>
{% endblock content %}

templates/core/detailS.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del estadio
{% endblock title %}

{% block content %}
  <h1>Detalles del estadio</h1>
    <p>Numero: {{ stadiums.codigo }}</p>
    <p>Nombre: {{ stadiums.nombre }}</p>
    <p>Capacidad: {{ stadiums.capacidad }}</p>
    <p>Largo del estadio (Yardas): {{ stadiums.largo }}</p>
    <p>Ancho del estadio (Yardas): {{ stadiums.ancho }}</p>
    <p>Propietario: {{ stadiums.propietario.nombre }}</p>
  
  <a href="{% url 'core:listS' %}" class="btn btn-outline-warning">Regresar</a>
{% endblock content %}

templates/core/detailT.html
{% extends "base/base.html" %}

{% block title %}
  Detalles del equipo
{% endblock title %}

{% block content %}
  <h1>Detalles del equipo</h1>

    <p>Numero: {{ teams.codigo }}</p>
    <p>Nombre: {{ teams.nombre }}</p>
    <p>Sede: {{ teams.sede }}</p>
    <p>Propietario: {{ teams.propietario.nombre }}</p>
  
  <a href="{% url 'core:listT' %}" class="btn btn-outline-warning">Regresar</a>
{% endblock content %}

templates/core/listO.html
{% extends 'base/base.html' %}

{% block title %} Lista de Propietarios {% endblock title %}

{% block content %}

    <br>
    <a href="{% url 'core:createO' %}" class="btn btn-outline-success form-control">Añadir nuevo propietario</a>
    <br>
    <h1>Listado de propietarios</h1>
    <table class="table table-striped table-hover">
        <thead>
            <th>Numero</th>
            <th>Nombre Completo</th>
        </thead>
        <tbody>
            {% for Owner in Owners %}
                <tr>
                    <td>{{ Owner.numero }}</td>
                    <td>{{ Owner.nombre }}</td>
                    <td><a href="{% url 'core:detailO' Owner.pk %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:UpdateO' Owner.pk %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{% url 'core:deleteO' Owner.pk %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

templates/core/listP.html
{% extends 'base/base.html' %}

{% block title %} Lista de Jugadores {% endblock title %}

{% block content %}

    <br>
    <a href="{% url 'core:createP' %}" class="btn btn-outline-success form-control">Añadir nuevo jugador</a>
    <br>
    <h1>Listado de jugadores</h1>
    <table class="table table-striped table-hover">
        <thead>
            <th>Numero</th>
            <th>Nombre Completo</th>
            <th>Posicion</th>

        </thead>
        <tbody>
            {% for player in Players %}
                <tr>
                    <td>{{ player.numero }}</td>
                    <td>{{ player.nombreC }}</td>
                    <td>{{ player.posicion }}</td>
                    <td><a href="{% url 'core:detailP' player.numero %}" class="btn btn-outline-info"> Detalles </a></td>
                    <td><a href="{% url 'core:UpdateP' player.numero %}" class="btn btn-outline-warning"> Actualizar</a></td>
                    <td><a href="{% url 'core:deleteP' player.numero %}" class="btn btn-outline-danger">Eliminar</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

templates/core/team_players.html
{% extends 'base/base.html' %}

{% block title %} Lista de Equipos y Jugadores {% endblock title %}

{% block content %}

    <br>
    <br>
    <h1>Listado de Equipos y jugadores</h1>
    <table class="table table-striped table-hover">
        <thead>
            <th>Numero</th>
            <th>Nombre Completo</th>
            <th>Posicion</th>
            <th>Equipo</th>

        </thead>
        <tbody>
            {% for player in Players %}
                <tr>
                    <td>{{ player.numero }}</td>
                    <td>{{ player.nombreC }}</td>
                    <td>{{ player.posicion }}</td>
                    <td>{{ player.equipo.nombre }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}